[package]
name = "bf6-voice-switcher"
version = "1.0.0"
edition = "2021"
authors = ["JohnsonRan"]
description = "战地6语音切换工具"

[dependencies]
eframe = "0.33"
rfd = "0.16"
fs_extra = "1.3"

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"
